def init_game_state() -> dict:
    return {
        "started": False,
        "game_over": False,
        "ending": None,
        "ending_summary": "",
        "turn": 1,
        "current_event": None,
        "event_cooldown": 0,
        "milestones_seen": [],
        "arc": {
            "childhood": "Childhood is where discipline, trust, and identity first take shape.",
            "teen": "Teen years test peer pressure, school choices, love, and early shortcuts.",
            "adult": "Adulthood turns habits into bills, family responsibility, and long-term consequences.",
        },
        "story_flags": {
            "school_suspensions": 0,
            "mentor_support": 0,
            "community_path": 0,
            "rivalry_level": 0,
            "relationship_commitment": 0,
            "dropout_risk": 0,
            "creative_talent": 0,
            "athletic_talent": 0,
            "recovery_steps": 0,
            "provider_pressure": 0,
            "structured_momentum": 0,
            "risk_momentum": 0,
            "family_momentum": 0,
            "community_momentum": 0,
            "unlocked_school_path": False,
            "unlocked_risk_path": False,
            "unlocked_family_path": False,
            "unlocked_community_path": False,
        },
        "world": {
            "neighborhood": "Southside Terrace",
            "rent_due": 140,
            "monthly_bills": 65,
            "school_quality": 50,
            "opportunity": 45,
            "school_name": "Cedar Heights Academy",
            "favorite_hangouts": ["corner store", "basketball courts", "bus stop", "community center"],
        },
        "household": {
            "guardian": {"name": "Denise", "role": "Guardian", "bond": 58},
            "sibling": {"name": "Marcus", "role": "Sibling", "bond": 52},
            "partner": {"name": "None", "role": "Partner", "bond": 50, "active": False},
        },
        "log": [
            "Life begins with pressure, potential, and people depending on you.",
        ],
        "player": {
            "name": "",
            "background": "Balanced",
            "life_stage": "Childhood",
            "age": 10,
            "cash": 60,
            "debt": 0,
            "stress": 12,
            "discipline": 50,
            "morality": 55,
            "temptation": 45,
            "family_bond": 55,
            "education": 50,
            "reputation": 0,
            "relationship_trust": 50,
            "legal_risk": 0,
            "hope": 55,
            "career_progress": 0,
            "street_influence": 0,
            "income": 0,
            "housing_stability": 60,
            "neighborhood_reputation": 0,
            "has_child": False,
            "school_record": 55,
            "confidence": 50,
        },
    }
